### ISSUE TITLE
add library support

### ISSUE THREAD

**Issue by chrisguttandin** [cexbrayat/angular-cli-diff#2]
Hi @cexbrayat,

many thanks for creating and maintaining this repo. It is always the first thing I check when there is a new version of the CLI.

I wonder if it would be possible to create an application with a library instead of "only" creating an app? It would of course break the history and will generate a bit of noise for those who are only interested in a generated app. Do you think it would make sense to create a separate repo for that?

**Comment by cexbrayat** [comment]
👋 @chrisguttandin 

And thank you for the kind words!

I think it would indeed add too much noise here, I'd like to keep it small. I used to generate a service, component, pipe, etc, but rolled it back as the important part is just the main configuration.

So a new repo is probably the right way to go. If you feel like it, you can fork the repo and tweak the main script `newVersion.sh` to make it generate a library as well, probably just starting from version 6.0. I'm going to close the issue, but if you give it a try and need a hand, feel free to ping me!

**Comment by chrisguttandin** [comment]
Hi @cexbrayat, thanks for the quick response. I can totally understand your decision.

I guess I have to think a bit more deeply about what I should do. If I do a fork for a library, then why not also doing a fork for a server rendered app. Or why not also adding a version for an app with routing enabled. ...

Maybe it's best to just not do it at all. :-)

**Comment by ersimont** [comment]
I would also find library support very helpful. FWIW, I see it as different from generating services, components, etc, because generating a library actually add modifies config, for example installing a compatibly version of `ng-packagr`, adding paths to `tsconfig.json`, and a whole project to `angular.json` that does not exactly match any of the existing ones.

I think for now I'll probably continue generating diffs manually on my own machine for the versions I'm upgrading from/to - but I agree with `chrisguttandin`: this setup is great when I can use it for non-library projects! Much nicer than doing it manually. It would be awesome if anyone starts a project that generates a library, too.

**Comment by cyrilletuzi** [comment]
First, thanks a lot for this repo which is very very helpful. 👍 

I agree with @ersimont: librairies are not like other schematics: they add a lot of configuration files, and configuration is even more important for librairies to avoid issues with new versions of Angular. As an author of a widely used Angular library myself, I can say it's a lot of work to stay up to date, as there is even less documentation than for classic applications.

@cexbrayat I understand that it would add noise. So instead, as the whole process seems to be fully automated, would it be possible to keep the current list and add another one for libraries?

**Comment by cexbrayat** [comment]
All right, you all convinced me!

Here is https://github.com/cexbrayat/angular-cli-library-diff a dedicated repo for library maintainers, starting from version 8.0.0.

For example here are the differences between [9.0.0-rc.10...9.0.0-rc.11](https://github.com/cexbrayat/angular-cli-library-diff/compare/9.0.0-rc.10...9.0.0-rc.11). Enjoy!

**Comment by cyrilletuzi** [comment]
@cexbrayat Thank you so much!

**Comment by ersimont** [comment]
Fancy! Thank you - this will simplify things for me :)
