### ISSUE TITLE
Generate in strict mode

### ISSUE THREAD

**Issue by cyrilletuzi** [cexbrayat/angular-cli-diff#3]
First, I already told you in another issue, but thanks again for this tool, it saves me so much time!

Angular CLI 9 added a new `--strict` option for `ng new`, with stricter compiler options. In Angular 10, it is now part of the prompt questions when doing `ng new`. And while the default is still `false` for now for legacy reasons,`true` is the recommended way and will become the default in a later version.

As this option manages a lot of configuration, it would be good to generate with `--strict` to be able to track the changes about this.

If you are OK, I've done the PR: #4

**Comment by cexbrayat** [comment]
Agreed, thank you for the PR 👍

**Comment by cyrilletuzi** [comment]
Closing as it's done.

**Comment by cexbrayat** [comment]
Yes, and I regenerated the versions from next.4 to reflect the flag. We can see your addition in tslint.json in rc.2, looks like it works 👌
